### ISSUE TITLE
Launches as transparent window

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/com.brave.Browser#96] opened 2021-12-13 18:37 UTC
![image](https://user-images.githubusercontent.com/14835120/145869107-5b2d275e-72e8-45e3-95db-68f0fd9e3fd3.png)

I am on Nvidia and Wayland. Chrome flatpak does work as you can see.

**Comment by rany2** [comment] 2021-12-13 19:19
Anything peculiar about your Brave's config? Anything in `~/.var/app/com.brave.Browser/config/brave-flags.conf`?

**Comment by alvarlagerlof** [comment] 2021-12-13 23:26
I don't have that file, so I probably have no flags. But I must add that the browser now has launched and is working. I did no updates in between or anything like that. So I don't know what changed.

**Comment by rany2** [comment] 2021-12-14 16:17
I'm closing this issue because NVIDIA+Wayland is very recent (just yesterday) and the bugs affect other Flatpak apps as well. I'll give Brave/Chrome/runtimes/etc (whatever the source of the issue is) some time to fix it. 

Reopen if this issue is not NVIDIA+Wayland only.

**Closed by rany2** 2021-12-14 16:17 UTC

**Comment by jlnr** [comment] 2025-06-15 15:05
Sorry for off-topic, but if anyone else finds this issue but does not even use Nvidia... you might just have removed too many permissions from the Brave flatpak, it needs device access to find graphics drivers. :) A noob is me.
