### ISSUE TITLE
Blurry/pixelated, incorrect scaling due to XWayland

### ISSUE THREAD

**Issue by antonok-edm** [flathub/com.brave.Browser#330] opened 2023-04-25 00:28 UTC
I've been testing Brave on a OnePlus 6 with Phosh on postmarketOS. By default the screen is blurry/heavily pixelated. The Chromium Flatpak doesn't have the same issue. In Chromium, `about://gpu` showed `scale=3` under `Display(s) Information > Info`, versus Brave which showed `scale=1`. Chromium also appears to automatically detect and use Wayland, while Brave still forces X11.

I discovered the `--ozone-platform-hint=auto` flag, which allows Brave to automatically select Wayland when it's available, otherwise falling back to X11. Setting it removed the pixelation entirely (see screenshots).

<details>
<summary>Screenshots</summary>

![20230330_22h46m10s_grim](https://user-images.githubusercontent.com/22821309/234140695-a62e34ed-7c9a-4bd1-bc96-be531e5e802f.png)
_Pixelation with default config. Normally, everything is 2x as large but equally blurry; here I've also used `--force-device-scale-factor=X`._

![20230424_16h48m31s_grim](https://user-images.githubusercontent.com/22821309/234140846-c44e458b-18d2-4b00-8a31-860b4e519981.png)
_No more pixelation after passing `--ozone-platform-hint=auto`. I still need to figure out how to make the window narrower, but at least this is the same way Chromium behaves._
</details>

I'm not sure how the Chromium Flatpak solves this issue since I couldn't find that flag mentioned anywhere. That being said, if it's possible to add `--ozone-platform-hint=auto` here, I think it would be an improvement at least.

**Comment by milkknife** [comment] 2023-04-25 14:14
Since I have x11 disabled by default, I use `--ozone-platform=wayland` to get chromium-based flatpaks to start. Then, I go to `chrome://flags` and search for "ozone" -- I set it to "Wayland" so that the flag is persistent. This the popular solution that's been known for a while now. 

Have you tried brave (non-flatpak) to see if it defaults to x11?

**Comment by antonok-edm** [comment] 2023-04-25 16:44
I haven't been able to try that, unfortunately. postmarketOS is Alpine-based; due to the lack of glibc it's hard to get Brave running outside of a container/sandbox.

**Comment by rany2** [comment] 2023-05-18 09:49
Is this issue fixed in 1.51.118 or better?

**Comment by refi64** [comment] 2023-05-19 20:22
> Chromium also appears to automatically detect and use Wayland, while Brave still forces X11.

It...doesn't, I'm not sure how it ended up using Wayland for you. But I'd imagine you're just experiencing weird X-isms that are only reproducible on Phosh or similar.

**Closed** 2024-02-16 22:25 UTC
