### ISSUE TITLE
Missing some useful filesystem permissions by default

### ISSUE THREAD

**Issue by x80486** [flathub/com.brave.Browser#1] opened 2020-10-12 14:32 UTC
I think `Brave` should have access to some other filesystem locations by default:

```yaml
- "--filesystem=xdg-documents"
- "--filesystem=xdg-download"     # ...already set
- "--filesystem=xdg-music"
- "--filesystem=xdg-videos"
```

While most of the actions would be to access `Downloads` to store downloaded archives/files, there are other actions like `Import Bookmarks` and `Upload` files that are also as important (and often used) and usually rarely use `Downloads` as default location.

> I understand all of that can be added/changed via the CLI or using `Flatseal`, but I'm arguing about setting some defaults without compromising security (in this case).

**Comment by analotia** [comment] 2020-10-12 15:49
Unfortunately I'm not sure if flathub would accept giving this many permissions by default. You could use Flatseal or flatpak override to give it those permissions. 

I just used these permissions because they're the same permissions used by the Firefox flatpak.

**Comment by analotia** [comment] 2020-10-12 15:53
Also I don't think I could do anything regarding the "Import bookmarks" and "Upload" issue. There is nothing I could do and it isn't desirable for the flatpak to be able to access all host files.

**Comment by x80486** [comment] 2020-10-12 17:11
I didn't state `host` or `home` access, but some specific locations.

If you install Brave today and try to access any file, all you will be able to see is `Downloads`. Probably Electron-based applications uses a _different way_ to access the filesystem, but if you see the manifest for Chrome (which is more similar to Brave than Firefox), you will see that it has all those permissions applied by default — and it works accordingly.

**Comment by bilelmoussaoui** [comment] 2020-10-12 17:17
> I didn't state `host` or `home` access, but some specific locations.
> 
> If you install Brave today and try to access any file, all you will be able to see is `Downloads`. Probably Electron-based applications uses a _different way_ to access the filesystem, but if you see the manifest for Chrome (which is more similar to Brave than Firefox), you will see that it has all those permissions applied by default — and it works accordingly.

Yes electron apps are not using the portals. Firefox does. There's a WIP merge request to fix that in electron but until it's merged, I tend to prefer restricted permissions while keeping the basic functionalities working.

**Comment by analotia** [comment] 2020-10-13 14:10
I'll keep this issue open until we get that patch. I don't think making the flatpak less restrictive is the way to go.

**Comment by x80486** [comment] 2020-10-13 14:15
OK, I'll make the changes on my end then :man_shrugging: ...because as it stands today, it's not usable in that regard.

I think those changes should go in effect and then another issue should be created to track Electron fix(es) for using portals, then revert the changes from this ticket.

**Comment by xinyazhang** [comment] 2020-10-15 21:34
Another problem I noticed is, when I'm using Brave in flatpak, the cookies would be lost whenever I closed the browser and left for a while.
It seems the `config` directory is not persistent and will be deleted after closing the sandbox.

**Comment by analotia** [comment] 2020-10-16 17:29
Weird because I had that problem and thought I fixed it. I'll recheck 
again to check what's going on and see if I could reproduce.

**Comment by analotia** [comment] 2020-10-19 06:02
> Another problem I noticed is, when I'm using Brave in flatpak, the cookies would be lost whenever I closed the browser and left for a while.
> It seems the `config` directory is not persistent and will be deleted after closing the sandboxed app.

Could you give me the output of `bash -c 'ls -l $(which bwrap)`? This is to check if SETUID or userns mode is used

**Comment by barthalion** [comment] 2020-10-23 08:56
> Another problem I noticed is, when I'm using Brave in flatpak, the cookies would be lost whenever I closed the browser and left for a while.
> It seems the `config` directory is not persistent and will be deleted after closing the sandboxed app.

It works fine on my end.

I have been using it on and off for the last few days and I'm somewhat confident to have it published to regular Flathub. I haven't encountered any major issues.

**Comment by elechner** [comment] 2020-10-25 21:35
> > Another problem I noticed is, when I'm using Brave in flatpak, the cookies would be lost whenever I closed the browser and left for a while.
> > It seems the `config` directory is not persistent and will be deleted after closing the sandboxed app.
> 
> Could you give me the output of `bash -c 'ls -l $(which bwrap)'`? This is to check if SETUID or userns mode is used

I have the same issue on a fresh install. 
---
bash -c 'ls -l $(which bwrap)'
-rwxr-xr-x. 4 root root 74544 Jan  1  1970 /usr/bin/bwrap

**Comment by JayDoubleu** [comment] 2020-11-17 15:08
Same issue here, the browser does not persist the cookies. After reboot all of them are gone. Also it think's its not the default browser on each reboot.

**Comment by rany2** [comment] 2020-12-10 17:38
Filesystem permissions @x80486 requested got added again

**Closed** 2020-12-10 17:37 UTC
