### ISSUE TITLE
Brave window is losing focus on mouse click after being switched to foreground

### ISSUE THREAD

**Issue by Zlopez** [flathub/com.brave.Browser#32] opened 2021-03-31 11:49 UTC
I started to have really annoying issue with flatpak Brave recently.

I'm using it now as a primary browser (thanks for the work!), but after switching to Fedora 34 Beta Silverblue I noticed a really strange behavior. Every time I switch to Brave (using either Activities overview in GNOME 40 or Alt+Tab) the first or first two mouse click are consumed by the application behind it and the focus is switched to this application.

**How to reproduce:**
1. Open any application in maximized window (I usually have LBRY behind it or Tutanota client)
2. Open Brave
3. Switch to Brave (Activities in GNOME 40 or Alt+Tab)
4. Click on anything inside Brave

**Expected result:**
The click is consumed by Brave

**Actual result:**
The application behind it gains focus and consumes the click

**Other things I noticed in this behavior:**
* This is happening only on Wayland
* This is happening only on my left most monitor (three monitor setup and this is not a primary monitor)
* Started to happen after update to GNOME 40 in Fedora 34 Beta
* Only happening on Brave browser (otherwise I would report this on Fedora bug tracker)

**Comment by TheEvilSkeleton** [comment] 2021-03-31 14:03
Thank you for the detailed report!

I'm using Fedora Silverblue 34 as well, but I am not experiencing this issue.


https://user-images.githubusercontent.com/50847364/113156662-30bcb800-9208-11eb-8792-be11e45a5b15.mp4

Perhaps it's a Fedora 34 issue? Have you tried on another user?

**Comment by Zlopez** [comment] 2021-03-31 14:43
I tried to record it, but OBS Studio doesn't show any output on Wayland and GNOME screen cast doesn't show the error, but the cursor just disappear when clicking anywhere in Brave window. Unfortunately this is not shown in the captured video :-(

For me this looks like some issue in Wayland compositor and Brave and multi-monitor setup. Not sure why it doesn't show up anywhere else.

**Comment by Zlopez** [comment] 2021-03-31 14:53
I was able to record the issue with my phone

https://user-images.githubusercontent.com/6943409/113164575-8497c300-9241-11eb-9e61-5ac0b18b18c3.mp4

As you can see, when I click the window behind gets focus.

**Comment by TheEvilSkeleton** [comment] 2021-03-31 17:57
> I tried to record it, but OBS Studio doesn't show any output on Wayland and GNOME screen cast doesn't show the error, but the cursor just disappear when focusing the Brave window. Unfortunately this is not shown in the captured video :-(

You should try out the beta version of the OBS Studio app (it's the one I used for screensharing in Wayland).

But again, have you tried to reproduce the issue? I haven't been able to reproduce it.

**Comment by Zlopez** [comment] 2021-03-31 19:24
@TheEvilSkeleton Did you looked at the video? I can reproduce it every time.

**Comment by TheEvilSkeleton** [comment] 2021-03-31 19:27
Sorry for being unclear. I meant to ask if you were able to reproduce it on another user.

**Comment by Zlopez** [comment] 2021-03-31 19:35
I reproduced it on another machine right now.

**Comment by Zlopez** [comment] 2021-03-31 19:43
One more thing I noticed, the issue can't be reproduced on primary monitor.

**Comment by TheEvilSkeleton** [comment] 2021-03-31 19:52
Oh! I was finally managed to reproduce it.

Okay, so I ran `flatpak run com.brave.Browser --enable-features=UseOzonePlatform --ozone-platform=wayland` to make Brave run on native Wayland. This fixed the issue for me. Can you try it and report it to me back?

**Comment by Zlopez** [comment] 2021-03-31 20:13
The workaround works for me.

It's probably a XWayland issue, I reported it on [Fedora bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1945412).

**Comment by refi64** [comment] 2021-03-31 20:33
Yeah if I had to guess this is definitely not something we can control, so it would be a bug in one of XWayland or whatever compositor you're using.

**Comment by Zlopez** [comment] 2021-04-08 13:15
There is already a merge request with fix for it in upstream https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1773

Do we want to left this open and wait till this will be released upstream? Or close it because it's not an issue in the flapaked brave?

**Comment by rany2** [comment] 2021-04-23 07:28
Closing this issue because it's not related to flatpak brave

**Closed by rany2** 2021-04-23 07:28 UTC
