### ISSUE TITLE
Flickering and painting black with mouse

### ISSUE THREAD

**Issue by alvarlagerlof** [flathub/com.brave.Browser#98] opened 2021-12-13 23:56 UTC
https://user-images.githubusercontent.com/14835120/145907805-0c6b423a-a283-4944-a69b-337e34a8bce8.mp4

**Comment by TheCultLeader666** [comment] 2021-12-14 00:04
Everything's fine here, might it be a graphics issue specific to you?

**Comment by alvarlagerlof** [comment] 2021-12-14 00:08
Idk, it's the latest Nvidia, mutter and wayland. Everything else works fine and this only appears sometimes. This was on the background of a popup.

**Comment by JayDoubleu** [comment] 2021-12-14 14:17
Mine just started jumping up and down like a jelly on web view lol.

**Comment by alvarlagerlof** [comment] 2021-12-14 15:07
@JayDoubleu Like frames snapping back and then jumping forward? Like this?

https://user-images.githubusercontent.com/14835120/146024323-36ac7646-c06b-4ed6-9c40-9d8951bd1086.mp4

**Comment by TheEvilSkeleton** [comment] 2021-12-14 15:09
Are you able to reproduce it in Brave rpm/deb?

**Comment by alvarlagerlof** [comment] 2021-12-14 15:11
Am on silverblue, don't want to layer it ideally.

**Comment by TheEvilSkeleton** [comment] 2021-12-14 15:12
Perhaps you can use Toolbx? You can install Brave rpm in the container and run it from there.

**Comment by alvarlagerlof** [comment] 2021-12-14 15:14
No gpu acceleration when doing that. Nvidia.

**Comment by TheEvilSkeleton** [comment] 2021-12-14 15:15
So what flags are you using when using the Flatpak?

**Comment by rany2** [comment] 2021-12-14 15:18
@TheEvilSkeleton https://github.com/flathub/com.brave.Browser/issues/96#issuecomment-993005448

**Comment by rany2** [comment] 2021-12-14 15:20
> No gpu acceleration when doing that. Nvidia.

Nvidia + Wayland isn't the best combo. It is known to have a lot of issues, go back to Xorg.

**Comment by rany2** [comment] 2021-12-14 15:46
@alvarlagerlof Could you screenshot your `chrome://gpu` on Brave and on Chrome so I could compare the two?

**Comment by alvarlagerlof** [comment] 2021-12-14 15:54
@rany2 Wayland + Nvidia just got support for GBM since mutter 41.2 from yesterday, so there should in theory be greater compatibility now. I cannot launch chrome now due to another bug.

**Comment by alvarlagerlof** [comment] 2021-12-14 15:57
https://user-images.githubusercontent.com/14835120/146033342-5bdee280-2a8d-4fca-bd16-06c2529f7b72.mp4

**Comment by alvarlagerlof** [comment] 2021-12-14 16:00
Heh! This happens on "first boot" after switching from using either chrome or brave on xorg to going to wayland. After like 30mins they usually start working.

**Comment by alvarlagerlof** [comment] 2021-12-14 16:03
I just want to know where this issue really lies, I have some trouble getting steam games in flatpak launching at all too so.

**Comment by TheEvilSkeleton** [comment] 2021-12-14 16:05
God, what the fuck is this. Can you try the Brave rpm from a Toolbx container and see if it's a Flatpak issue or an upstream issue? Also, can you try running Brave on Wayland?

**Comment by rany2** [comment] 2021-12-14 16:17
I'm closing this issue because NVIDIA+Wayland is very recent (just yesterday) and the bugs affect other Flatpak apps as well. I'll give Brave/Chrome/runtimes/etc (whatever the source of the issue is) some time to fix it. 

Reopen if this issue is not NVIDIA+Wayland only.

**Closed by rany2** 2021-12-14 16:17 UTC

**Comment by alvarlagerlof** [comment] 2021-12-14 19:41
> Can you try the Brave rpm from a Toolbx container and see if you can reproduce this within the container? Also, can you try running Brave on Wayland?

@TheEvilSkeleton I cannot use flatpak, because that has no GPU acceleration at all, making things like scrolling laggy. This is on Wayland. Xorg has no issues.

**Comment by JayDoubleu** [comment] 2021-12-14 19:42
On toolbx if you install the same drivers as on the host you should have full acceleration

**Comment by alvarlagerlof** [comment] 2021-12-14 21:03
> On toolbx if you install the same drivers as on the host you should have full acceleration

I don't know of anyone who's successfully done that on Nvidia.

**Comment by JayDoubleu** [comment] 2021-12-14 21:53
That issue looks quite old. Recently there were more gfx packages added not only to Silverblue but also to toolbox.
I was trying it roughly about 6 weeks ago on proprietary driver.

**Comment by alvarlagerlof** [comment] 2021-12-15 19:03
> That issue looks quite old. Recently there were more gfx packages added not only to Silverblue but also to toolbox. I was trying it roughly about 6 weeks ago on proprietary driver.
> 
> If I remember correctly I had to install below but thats no longer necessary AFAIK.
> 
> ```
>             , "mesa-vulkan-drivers"
>             , "mesa-dri-drivers"
>             , "libglvnd-glx"
> ```
> 
> I was using brave browser from their RPM repo

That is mesa? I use Nvidia.

**Comment by JayDoubleu** [comment] 2021-12-15 19:19
Anyways, I had toolbox working not only with proper acceleration working in brave but also cuda.

**Comment by alvarlagerlof** [comment] 2021-12-15 19:26
So Installing the nvidia drivers from rpmfusion or what? https://rpmfusion.org/Howto/NVIDIA

**Comment by JayDoubleu** [comment] 2021-12-15 21:59
If I remember correctly I had to install drivers properly on the host with all akmods etc from guide you posted.

Then on toolbox `dnf install xorg-x11-drv-nvidia xorg-x11-drv-nvidia-cuda`  + those packaged I mentioned earlier.

**Comment by alvarlagerlof** [comment] 2021-12-15 22:53
That is interesting, I was able to start glxgears with that, something I could not before. But it's a black windows, probably an xwayland issue. And flickering in chromium-based things, also probaby a wayland issue.

**Comment by JayDoubleu** [comment] 2021-12-15 22:55
I'm not sure about Wayland support.

I was disabling Wayland from /etc/gdm/custom.conf entirely. I remember having issues without it

**Comment by alvarlagerlof** [comment] 2021-12-15 23:01
Yeah it's supposed to work better since a few days ago but I think what happend is that everyone had special eglstreams code trigger for wayland and now it's not supposed to anymore.
